# Usar uma imagem base do Maven para compilar o projeto
FROM maven:3.8.5-openjdk-17 AS build

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar o pom.xml e o código fonte do projeto para dentro do container
COPY pom.xml .
COPY src ./src

# Compilar o projeto usando Maven
RUN mvn clean package -DskipTests

# Usar uma imagem base do OpenJDK para rodar a aplicação
FROM openjdk:17-jdk-slim

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar o .jar gerado no estágio anterior para o novo container
COPY --from=build /app/target/*.jar app.jar

# Expor a porta que a aplicação vai utilizar
EXPOSE 8080

# Comando para executar a aplicação
CMD ["java", "-jar", "app.jar"]
